### ISSUE TITLE
Multiple Subdomains?

### ISSUE THREAD

**Issue by NeodymiumPhish** [parker-hemphill/godaddy-dns-updater#2]
What's the recommendation for running this against multiple subdomains? I'd like to have at least 2, probably more, subdomains all pointed to the same server, which the @ record stays someplace else.

Thanks!

**Comment by parker-hemphill** [comment]
You could run two containers, here's an example docker-compose.  You can variable this and other docker containers by creating a file named `.env` in the directory containing your docker-compose.yaml file with the following setup:
```
DOMAIN=some-site.com
DDNS_API=<godaddy API key>
```
In this example *some-site.com* is your domain and will **NOT** be updated, **siteone.some-site.com** and **sitetwo.some-site.com** will be updated independently

```
version: "3.0"
services:
  first-site:
    image: parkerhemphill/godaddy-dns-updater
    container_name: ddns-site-one
    environment:
      - PUID=1000
      - PGID=1000
      - DOMAIN=${DOMAIN}
      - SUB_DOMAIN=siteone
      - API_KEY=${DDNS_API}
      - DNS_CHECK=900
      - TIME_ZONE=America/New_York
    volumes:
      - /tmp:/tmp
    restart: unless-stopped

  site-two:
    image: parkerhemphill/godaddy-dns-updater
    container_name: ddns-site-two
    environment:
      - PUID=1000
      - PGID=1000
      - DOMAIN=${DOMAIN}
      - SUB_DOMAIN=sitetwo
      - API_KEY=${DDNS_API}
      - DNS_CHECK=900
      - TIME_ZONE=America/New_York
    volumes:
      - /tmp:/tmp
    restart: unless-stopped

**Comment by parker-hemphill** [comment]
Gonna go ahead and close issue, feel free to re-open or create a new one if there are issues

**Comment by parker-hemphill** [comment]
In the latest release I've added the ability to sync multiple subdomains in the same container, simply pass them as a "|" delimited string such as `- SUB_DOMAIN=subdomain1|subdomain2|subdomain3`.  Can also be ran as single container for each subdomain if preferred.  This container uses Alpine Linux as its base and has a very lite footprint
