### ISSUE TITLE
Sleep Invalid Number error

### ISSUE THREAD

**Issue by bmcgonag** [parker-hemphill/godaddy-dns-updater#4]
Good Day running the latest pull from Docker Hub using Docker Compose. 

I get the following in my output:

```
xxx.xxx.xxx.103, no update needed
godaddy-ddns    | sleep: invalid number 'etc'
godaddy-ddns    | [04/26/21 10:15 EDT] External DNS for bin.routemehome.org resolves to xxx.xxx.xxx.103, no update needed
godaddy-ddns    | sleep: invalid number 'etc'
godaddy-ddns    | [04/26/21 10:15 EDT] External DNS for bin.routemehome.org resolves to xxx.xxx.xxx.103, no update needed
godaddy-ddns    | sleep: invalid number 'etc'
godaddy-ddns    | [04/26/21 10:15 EDT] External DNS for bin.routemehome.org resolves to xxx.xxx.xxx.103, no update needed
godaddy-ddns    | sleep: invalid number 'etc'
godaddy-ddns    | [04/26/21 10:15 EDT] External DNS for bin.routemehome.org resolves to xxx.xxx.xxx.103, no update needed
godaddy-ddns    | sleep: invalid number 'etc'
godaddy-ddns    | [04/26/21 10:15 EDT] External DNS for bin.routemehome.org resolves to xxx.xxx.xxx.103, no update needed
godaddy-ddns    | sleep: invalid number 'etc'
godaddy-ddns    | [04/26/21 10:15 EDT] External DNS for bin.routemehome.org resolves to xxx.xxx.xxx.103, no update needed
godaddy-ddns    | sleep: invalid number 'etc'
```

It repeats very quickly as you can see, as I think the sleep counter is not getting the ENV for 600 for some reason.

**Comment by parker-hemphill** [comment]
Yeah, something isn't passing the ENV, I'll take a look after work tonight.  Are you running this on a RPI or 64bit Linux box?

**Comment by bmcgonag** [comment]
Additionally, I'm trying to update the wildcard subdomain "*", so not sure that is going to be handled properly as it show "bin.routemehome.org" in the output. Do I need to do something different to allow my wildcard subdomain to be updated?

**Comment by bmcgonag** [comment]
64 bit Linux Box by the way.

**Comment by parker-hemphill** [comment]
You should be able to use the domain to set wildcard.  I have “jellyfin.domain, plex.domain, etc” and only check domain.  I set the sub domains to point to “@“ in my GoDaddy DNS manager.  I also have a otherpc.domain that I update directly for ssh access to a remote box I have.  For that one I use the domain and subdomain ENV variables

**Comment by bmcgonag** [comment]
Excellent! thank you.

**Comment by bmcgonag** [comment]
I removed the sub-domain ENV and changed it in GoDaddy to have a CNAME pointing to my main domain A record.  

Now it runs fine.  Not sure if you want to see why that * subdomain caused that issue, but I can see someone wanting the main domain to point to one IP while * points somewhere else for wildcard subdomains.

**Comment by parker-hemphill** [comment]
Good catch on your part.  Glad you were able to fix it.  I'm going to take an action to address this corner case so it doesn't bite others in the future.
